main: yy.gourlitburo.yeyachat.Main
name: YeyaChat
version: 0.1.1
api-version: 1.14
author: Zack Guard
description: A chat format plugin with pinging and Markdown support.
commands:
  yeyachat:
    aliases: [yc]
    description: Manage YeyaChat.
    usage: "Usage: /yc reload"
    permission: yeyachat.manage
permissions:
  yeyachat.manage:
    default: op
  yeyachat.ping:
    default: true
  yeyachat.ping.immune:
    default: false
